Dbaas 2120
edriggers/zeppelin-notebooks pull request #11
Opened 2019-02-08 20:01 UTC by Ben-Epstein

2019-03-27 16:54 UTC, njnygaard commented
What is the pathway for getting these in new clusters? Is master pulled for all new clusters?

2019-03-27 16:55 UTC, Ben-Epstein commented
@njnygaard No, we will create a new release and update dcos-commons-vanilla to pull from the new one

2019-03-27 17:08 UTC, njnygaard approved these changes

2019-03-27 18:25 UTC, edriggers commented on README.md
> +|2CN9CP75G|8. Machine Learning / 1. Kmeans| |[json](https://github.com/splicemachine/zeppelin-notebooks/raw/master/2CN9CP75G/note.json) | |
I don't see any of these '8. Machine Learning' notebooks

2019-03-27 18:30 UTC, edriggers requested changes
A couple of comments that are in general to all notebooks:
1 - Clear the output before checking in notebook for paragraphs that are not 'md' paragraphs
2 - Format the JSON before checking in the file - In IntelliJ the command is Command Option L
3 - If you are making changes to existing notebooks please check them in with the same file names.  I know the name of the file changes in some scenarios but you can update the JSON and change the id (normally near the bottom of the json) to match the original value.  The reason for this is that it is hard to see what changed between the version you are checking in and the original version.
4 - If we are getting rid of the Data Engineering folder then we need to fix the numbering of the top level folders.

2019-03-28 20:41 UTC, Ben-Epstein commented
@edriggers  Regarding 3, I understand and will keep with that protocol from now on, but I don't think it's worth changing them for this PR, because it would require going into every notebook to change back which URL the previous notebook links to because each notebook in the series references the one after it.

2019-04-01 13:46 UTC, edriggers approved these changes

2019-04-01 13:47 UTC, merged